service: aplatam-contact # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs10
  project: ${env:PROJECT_ID}
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  sendEmail:
    handler: sendEmail
    events:
      - http: path
